title:              Still Waters
email:              hackerleon@foxmail.com
description:        Hackerleon Blog
author:             Hackerleon
baseurl:            ""
url:                "https://stillwaters.top"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    anchem
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-KZJPY920XT # out your google-analytics code

# Build settings
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# side bar
sidebar-about-description: "HackerLeon."
sidebar-avatar: /img/avatar-hackerleon-me.jpg

# theme
post-theme: [
    {
        title: "软件工程师系列",
        url: "#"
    },
    {
        title: "阿不成长树",
        url: "#"
    }
]
